### ISSUE TITLE
Use Reveal.js for slides?

### ISSUE THREAD

**Issue by andygup** [sean-olson-e/Angular-and-the-ArcGIS-API-for-JavaScript#13]
Might make sense to drop in Gavin's reveal deck. Keep content light and simple.

**Comment by andygup** [comment]
https://github.com/ArcGIS/dev-summit-2018-reveal-js

**Comment by sean-olson-esri** [comment]
I don't have enough experience presenting to have an opinion on this.  No access to the repo.  Whatever you both decide is fine with me.
