### ISSUE TITLE
Unable to use Angular CLI in current configuration -- configuring multiple apps in angular-cli.json

### ISSUE THREAD

**Issue by sean-olson-e** [sean-olson-e/Angular-and-the-ArcGIS-API-for-JavaScript#16]
With the current configuration, I am unable to create a component using the CLI.

**Comment by jwasilgeo** [comment]
Weird, I think I am seeing a problem, too, even though the docs claim that `ng generate component` supports the `--app` option: https://github.com/angular/angular-cli/wiki/generate-component

**Comment by jwasilgeo** [comment]
@sean-olson-e and @andygup I just pushed [a commit to the `master` branch](ca7e88afb1e93f0b073b4e110506757b0ad175ad) that will fix this.

There are a couple version bumps for deps in the package.json file, so please update your npm installations.  A global update of your Angular CLI installation also wouldn't hurt.

You can now do things like:
`ng generate component mytest --app 1-app-scaffolding`
