### ISSUE TITLE
sample apps should begin with latest "angular-cli-esri-map"

### ISSUE THREAD

**Issue by jwasilgeo** [sean-olson-e/Angular-and-the-ArcGIS-API-for-JavaScript#17]
Sample apps' code base should start from @andygup's https://github.com/ArcGIS/angular-cli-esri-map, correct?

Bringing this to @sean-olson-e's attention since there have been some updates by @andygup recently.

@andygup are there any pending updates remaining over at that repo?

Question for all 3 of us: do we need to support unit and functional tests for our sample apps for Dev Summit since @andygup's other repo is stripped down to the bare essentials?  I have no desire to do so for my own presentation topics.

I'll begin just by going in to the sample apps I'm currently working on ("esri-loader" and "arcgis types") and run my changes through a PR.

**Comment by sean-olson-e** [comment]
@jwasilgeo, I would rather not do anything with unit tests.  This just adds an additional layer of complexity to an hour-long talk.

**Comment by sean-olson-e** [comment]
Resolved
